In [1]:
import sys
sys.path.insert(0, './../Libs/')
import numpy as np
from HMM import HMMOptimizer
from ProbDistributor import Distributor, GenerateDistributionMatrix

In [2]:
AInit = np.array(
    [
        [0.1, 0.6, 0.3],
        [0.7, 0.1, 0.2],
        [0.3, 0.5, 0.2]
    ])

BInit = np.array(
    [
        [0.2, 0.1, 0.7],
        [0.4, 0.1, 0.5],
        [0.1, 0.6, 0.3]
    ])

piInit = np.array([0.3, 0.3, 0.4])

In [3]:
def ExecuteBallsAndUrns(A, B, pi, NSteps):
    states = []
    observations = []
    initState = Distributor(pi).Generate()
    states.append(initState)
    NSteps -= 1
    AGen = [Distributor(a) for a in A]
    BGen = [Distributor(b) for b in B]
    observations.append(BGen[initState].Generate())
    for _ in range(NSteps):
        states.append(AGen[states[-1]].Generate())
        observations.append(BGen[states[-1]].Generate())
    return (states, observations)

In [4]:
states, observations = ExecuteBallsAndUrns(AInit, BInit, piInit, 100)
print("States:\n{}".format(states))
print("Observations:\n{}".format(observations))

States:
[0, 2, 1, 0, 1, 0, 2, 0, 1, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 0, 2, 0, 2, 0, 2, 1, 0, 1, 0, 2, 2, 2, 1, 0, 2, 2, 1, 0, 1, 0, 2, 0, 2, 1, 1, 2, 0, 2, 1, 0, 1, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2, 1, 1, 2, 2, 1, 0, 1, 0, 1, 0, 1, 0, 1, 2, 1, 2, 0, 1, 0, 1, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0]
Observations:
[2, 0, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 0, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 0, 0, 0, 0, 0, 2, 0, 1, 1, 2, 0, 2, 1, 0, 2, 0, 1, 1, 2, 0, 0, 2, 1, 2, 2, 2, 2, 0, 1, 1, 2, 0, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 0, 2]


In [5]:
opt = HMMOptimizer(NStates = 3, NObsStates = 3).fit(np.array(observations), 1000000)
print(opt)

epsilon reached!, steps = 1498
A:
[[0.6354 0.     0.3646]
 [0.     0.7928 0.2072]
 [0.145  0.855  0.    ]]
B:
[[1.     0.     0.    ]
 [0.1985 0.3252 0.4764]
 [0.     0.     1.    ]]
pi:
[0. 0. 1.]
