In [1]:
import sys
sys.path.insert(0, './../Libs/')
import numpy as np
from HMM import HMMOptimizer
from ProbDistributor import Distributor, GenerateDistributionMatrix

In [2]:
AInit = np.array(
    [
        [0.1, 0.6, 0.3],
        [0.7, 0.1, 0.2],
        [0.3, 0.5, 0.2]
    ])

BInit = np.array(
    [
        [0.2, 0.1, 0.7],
        [0.4, 0.1, 0.5],
        [0.1, 0.6, 0.3]
    ])

piInit = np.array([0.3, 0.3, 0.4])

In [3]:
def ExecuteBallsAndUrns(A, B, pi, NSteps):
    states = []
    observations = []
    initState = Distributor(pi).Generate()
    states.append(initState)
    NSteps -= 1
    AGen = [Distributor(a) for a in A]
    BGen = [Distributor(b) for b in B]
    observations.append(BGen[initState].Generate())
    for _ in range(NSteps):
        states.append(AGen[states[-1]].Generate())
        observations.append(BGen[states[-1]].Generate())
    return (states, observations)

In [8]:
states, observations = ExecuteBallsAndUrns(AInit, BInit, piInit, 30)
print("States:\n{}".format(states))
print("Observations:\n{}".format(observations))

States:
[2, 1, 2, 1, 0, 1, 0, 1, 0, 2, 1, 0, 1, 1, 0, 2, 2, 2, 1, 0, 1, 0, 1, 2, 1, 0, 2, 2, 1, 0]
Observations:
[2, 1, 1, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 0, 2, 1, 1, 1, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 1, 2]


In [16]:
opt = HMMOptimizer(NStates = 3, NObsStates = 3).fit(np.array(observations), 1000000)
print(opt)

epsilon reached!, steps = 247
A:
[[8.17107120e-01 2.33830362e-31 1.82892880e-01]
 [2.51276734e-01 7.48723266e-01 2.25910334e-25]
 [4.55876629e-22 3.21785207e-01 6.78214793e-01]]
B:
[[1.27004408e-95 4.95997343e-01 5.04002657e-01]
 [4.23611930e-01 1.66376566e-64 5.76388070e-01]
 [3.20750859e-01 5.04793713e-23 6.79249141e-01]]
pi:
[1.00000000e+000 2.26579623e-142 0.00000000e+000]
