In [2]:
import sys
sys.path.insert(0, './../Libs/')
import numpy as np
from HMM import HMMViterbiStatePredictor

In [3]:
A = np.array(
    [
        [0.2, 0.4, 0.1, 0.3],
        [0.1, 0.2, 0.3, 0.4],
        [0.4, 0.3, 0.2, 0.1],
        [0.1, 0.5, 0.2, 0.2]
    ])

B = np.array(
    [
        [0.3, 0.3, 0.4],
        [0.2, 0.1, 0.7],
        [0.4, 0.1, 0.5],
        [0.1, 0.6, 0.3]
    ])

pi = np.array([0.25, 0.25, 0.25, 0.25])

In [5]:
viterbi = HMMViterbiStatePredictor(A, B, pi).fit([0, 2, 1, 1, 1, 0, 0, 2, 2])
print(viterbi)
print("Fitting probability: {}".format(viterbi.getFittingProb()))
print("Path: {}".format(viterbi.getPath()))

alpha:
[[7.50000000e-02 1.60000000e-02 1.20000000e-03 1.51200000e-04
  1.81440000e-05 2.17728000e-06 6.96729600e-07 1.39345920e-07
  1.39345920e-08]
 [5.00000000e-02 2.10000000e-02 6.40000000e-04 2.52000000e-04
  3.02400000e-05 7.25760000e-06 3.48364800e-07 1.95084288e-07
  3.90168576e-08]
 [1.00000000e-01 1.00000000e-02 6.30000000e-04 1.00800000e-04
  1.20960000e-05 5.80608000e-06 8.70912000e-07 8.70912000e-08
  2.92626432e-08]
 [2.50000000e-02 6.75000000e-03 5.04000000e-03 6.04800000e-04
  7.25760000e-05 1.45152000e-06 2.90304000e-07 6.27056640e-08
  2.34101146e-08]]
theta:
[[0. 2. 2. 3. 3. 3. 2. 2. 2.]
 [0. 0. 0. 3. 3. 3. 2. 0. 0.]
 [0. 2. 1. 3. 3. 3. 1. 2. 1.]
 [0. 0. 1. 3. 3. 3. 1. 0. 1.]]
Fitting probability: 3.90168576e-08
Path: [0, 2, 1, 3, 3, 3, 1, 0, 0]
